name: Download crsqlite

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "The repository to download crsqlite from"
        default: ""

      tag:
        description: "The tag to download crsqlite from"
        required: true

      branch:
        description: "The new branch to make commit to"
        required: false
        default: ""

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repository to runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download crsqlite
        run: |
          INPUT_REPO=${{ inputs.repo }}
          if [[ -z $INPUT_REPO ]]; then
            INPUT_REPO=${{ github.repository_owner }}
          fi
          TAG=${{ inputs.tag }} REPO=${INPUT_REPO} ./.buildkite/download-crsqlite.sh


      - uses: EndBug/add-and-commit@v9
        with:
          add: crates/corro-types
          new_branch: "${{ inputs.branch }}"
          message: "Update crsqlite to ${inputs.tag}"
          push: true
