name: Download crsqlite

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "The repository to download crsqlite from"
        default: ""

      tag:
        description: "The tag to download crsqlite from"
        required: true

      branch:
        description: "The branch to make commit to"
        required: false
        default: "main"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repository to runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download crsqlite
        run: |
          REPO=${{ inputs.repo }}
          if [[ -z $REPO ]]; then
            REPO=${{ github.repository_owner }}
          fi
          oses=("darwin-aarch64" "linux-aarch64" "linux-x86_64")

          for os in "${oses[@]}"; do
              if [[ $os == *"darwin"* ]]; then
                  EXT="dylib"
              else
                  EXT="so"
              fi
              curl -L -o crsqlite-${os}.zip https://github.com/${{ inputs.repo }}/cr-sqlite/releases/download/${{ inputs.tag }}/crsqlite-${os}.zip
              unzip -p crsqlite-${os}.zip > crates/corro-types/crsqlite-${os}.${EXT}
              rm crsqlite-${os}.zip
          done


      - uses: EndBug/add-and-commit@v9
        with:
          add: crates/corro-types
          message: "Update crsqlite to ${inputs.tag}"
          push: true
