name: Download crsqlite

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "The repository to download crsqlite from"
        required: true
        default: "${{ github.repository_owner }}"

      tag:
        description: "The tag to download crsqlite from"
        required: true
        default: "prebuild-test.site-db-version-6"

      branch:
        description: "The branch to make commit to"
        required: true
        default: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download crsqlite
        run: |
          if [[ ${{ matrix.os }} == *"darwin"* ]]; then
              EXT="dylib"
          else
              EXT="so"
          fi
          curl -L -o crsqlite-${{ matrix.os }}.zip https://github.com/${{ inputs.repo }}/cr-sqlite/releases/download/${{ inputs.tag }}/crsqlite-${{ matrix.os }}.zip
          unzip -p crsqlite-${{ matrix.os }}.zip > crates/corro-types/crsqlite-${{ matrix.os }}.${EXT}
          rm crsqlite-${{ matrix.os }}.zip
        with:
          matrix:
            os:
              - darwin-aarch64
              - linux-x86_64
              - linux-aarch64


      - uses: EndBug/add-and-commit@v9
        with:
          add: crates/corro-types
          message: "Update crsqlite to ${inputs.tag}"
          push: true
